# Generated by Django 5.2.10 on 2026-07-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("splits", "0002_group_groupexpense_groupmember_delete_split_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupexpense",
            name="category",
            field=models.CharField(default="General", max_length=50),
        ),
        migrations.AlterField(
            model_name="groupexpense",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
